### ISSUE TITLE
[FEATURE] 회원가입 완료, 학원키 입력 화면 구현

### ISSUE THREAD

**Issue by ms214** [2024-summer-project/AcademyManager_FE#6]
## 어떤 기능인가요?

> 회원가입 화면에서 학원키가 입력되면 홈으로 버튼을 출력하고 학원키가 입력되지 않으면 학원키 입력하기 버튼을 출력하여 학원키 입력 화면으로 넘어간다.

## 작업 상세 내용

- [x] 회원가입 환영 화면 구현
- [x] 학원키 입력화면 구현
- [x] 회원가입 화면에서 학원키 입력여부에 따라 버튼의 text와 기능을 다르게 구현
- [x] 마이페이지 UI 구현
- [x] 회원정보 UI 구현
- [x] 앱설정 UI 구현
- [x] 성적그래프, 성적조회 UI 구현
- [x] 공지목록 공지내용 조회 UI 구현

## 참고할만한 자료(선택)
[Fl_chart](https://github.com/imaNNeo/fl_chart/blob/main/repo_files/documentations/line_chart.md)

**Comment by ms214** [comment]
<img src='https://github.com/user-attachments/assets/2597a955-019f-4d71-9339-ee1702be14ac' width='300px'>
<img src='https://github.com/user-attachments/assets/1f149080-8eef-41b6-ae04-c12a10ae307b' width='300px'>
<img src='https://github.com/user-attachments/assets/04526ea0-23c5-41d5-a7a5-d29dce888dd9' width='300px'>
<img src='https://github.com/user-attachments/assets/ca69a721-d451-42db-a674-e4ca10340f9a' width='300px'>

- 개발 중 AppBar를 따로 파일로 빼면 좋을 것 같아 [04364cb](https://github.com/2024-summer-project/AcademyManager_FE/commit/04364cb555241304addaa54ba9338bb362cac9c4) 에서 추가 작업하였습니다.
- 그래프는 Fl_chart를 사용하였습니다.

**Comment by taeyun357** [comment]
![MyPage](https://github.com/user-attachments/assets/a283e029-06f5-42d6-8994-ca4fbe917bb7)
![MemberInfoEdit](https://github.com/user-attachments/assets/3dc89419-4d8f-4d48-bc7e-5b01144f7a2b)
![AppSettings](https://github.com/user-attachments/assets/3b0d8d95-6956-426f-bc27-129392735764)
![NoticeList](https://github.com/user-attachments/assets/1c05e684-eba9-430c-b26f-95ecf9eaaeb4)
![NoticeDetail](https://github.com/user-attachments/assets/d990c2b3-9d03-40d0-a5fc-b2994f4e5cb2)

**Comment by taeyun357** [comment]
![MyPage](https://github.com/user-attachments/assets/35150b9b-b346-4d54-82dd-56532ae82877)
![MemberInfoEdit](https://github.com/user-attachments/assets/ee763c45-fccc-442b-a0ea-b72e82850e10)
![AppSettings](https://github.com/user-attachments/assets/66108d3e-a0c9-4276-be7b-937b78793eef)
![NoticeList](https://github.com/user-attachments/assets/3812dca9-3ceb-4cf2-9a2b-2f250657b102)
![NoticeDetail](https://github.com/user-attachments/assets/2ae15e51-974a-41bf-9fbe-11c198858f80)

**Comment by taeyun357** [comment]
<img src="https://github.com/user-attachments/assets/53b10b6e-0fa5-402f-8bbb-fed1de4d9f1f" alt="MyPage" width="300px" />
<img src="https://github.com/user-attachments/assets/1d439410-49e1-42de-9132-6b916daa878d" alt="MemberInfoEdit" width="300px" />
<img src="https://github.com/user-attachments/assets/d50569b2-03d4-4213-a7e2-f0e745388003" alt="AppSettings" width="300px" />
<img src="https://github.com/user-attachments/assets/32e32fd3-bab5-4bcb-960e-df6a5f858d9f" alt="NoticeList" width="300px" />
<img src="https://github.com/user-attachments/assets/08868501-bdb5-4d43-a43b-636a5e66c808" alt="NoticeDetail" width="300px" />
